{
  "LiteBuildConfig": { "ignore_sys_prefix": false },
  "jupyter-config-data": {
    "collaborative": true,
    "@jupyterlab/collaboration-extension:webrtc": {
      "signalingServers": [
        "wss://signaling.yjs.dev",
        "wss://y-webrtc-signaling-eu.herokuapp.com"
      ]
    }
  }
}
