name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install --upgrade-strategy eager -r requirements.txt
          # (optional) show discovered lab extensions
          jupyter labextension list || true

      - name: Build JupyterLite to dist/
        run: |
          mkdir -p content
          cp -f README.md content/ || true
          # single clean build to dist/
          jupyter lite build --output-dir dist --debug

          # --- sanitize artifact against old RTC workspaces/paths ---
          rm -f dist/lab/workspaces/*.jupyterlab-workspace || true
          # rewrite any lingering "RTC:" to a safe relative root
          if grep -R '"RTC:' -n dist 2>/dev/null; then
            sed -i 's/"RTC:/"./g' $(grep -R -l '"RTC:' dist)
          fi

          # sanity: ensure static app exists
          test -f dist/dist/jupyter-lite.json || (echo "missing dist/dist/jupyter-lite.json"; ls -R dist; exit 1)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
